/*
 * Copyright (c) 2019 Dell Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 * LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
 * FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT.
 *
 * See the Apache Version 2.0 License for specific language governing
 * permissions and limitations under the License.
 */

/*
 * filename: nas_int_list.h
 */


#ifndef NAS_LINK_H_
#define NAS_LINK_H_

#include "std_llist.h"
#include "ds_common_types.h"
#include "nas_ndi_common.h"

#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct nas_list_s {
    std_dll_head port_list; //list of ports
    int port_count;
} nas_list_t;

typedef struct nas_list_node_s {
    std_dll entry;
    hal_ifindex_t ifindex; //Vlan Interface index generated by Linux kernel
    ndi_port_t ndi_port;   //npu and port id's for this interface
} nas_list_node_t;


nas_list_node_t *nas_get_first_link_node(std_dll_head *p_link_node_list);

nas_list_node_t *nas_get_next_link_node(std_dll_head *p_link_node_list,
                                        nas_list_node_t *p_link_node);

nas_list_node_t *nas_get_link_node(std_dll_head *p_link_node_list,
                                   hal_ifindex_t index);

void nas_insert_link_node(std_dll_head *p_link_node_list,
                          nas_list_node_t *p_link_node);

void nas_delete_link_node(std_dll_head *p_link_node_list,
                          nas_list_node_t *p_link_node);

void nas_delete_port_list(nas_list_t *p_link_node_list);

#ifdef __cplusplus
}
#endif

#endif /* NAS_LINK_H_ */
