#!/bin/bash -e

./nas_int_rpc_unittest
./nas_int_lag_unittest

if [ $(dpkg-query -W -f='${Status}' python-pytest 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
echo "Install pytest"
apt-get update
apt-get install -y python-pytest
fi

pytest -s ./test_nas_get_next_interface.py
pytest -s ./nas_hybrid_group_test.py
pytest -s ./nas_port_pkt_drop_test.py
pytest -s ./test_nas_get_ether_stats.py
